# Contexts are collections of variables that are accessible outside of the run commands. 
# You can think of them as variables which can be templated into the workflow file itself. 
# See the full list of contexts here. https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#contexts
name: contexts-example
on:
  push:
  pull:
jobs:
  use-contexts:
    strategy:
      matrix:
        greeting: [Hello, Howdy, Hey]
    runs-on: ubuntu-latest
    steps:
      -
        name: Print greeting
        run: echo $GREETING
        env:
          GREETING: ${{ matrix.greeting }}
      -
        name: Do work with a secret
        run: ./workRequiringASecret.sh
        env:
          A_SECRET: ${{ secrets.A_SECRET }}
      -
        name: Run only for pulls
        if: ${{ github.event == "pull" }}
        run: echo "Triggered by a pull request"          
